from handwritingBCI.pathlib_extension import Path

KEYS = ['__header__',
        '__version__',
        '__globals__',
        'neuralActivityCube_a',
        'neuralActivityCube_b',
        'neuralActivityCube_c',
        'neuralActivityCube_d',
        'neuralActivityCube_t',
        'neuralActivityCube_m',
        'neuralActivityCube_o',
        'neuralActivityCube_e',
        'neuralActivityCube_f',
        'neuralActivityCube_g',
        'neuralActivityCube_h',
        'neuralActivityCube_i',
        'neuralActivityCube_j',
        'neuralActivityCube_k',
        'neuralActivityCube_l',
        'neuralActivityCube_n',
        'neuralActivityCube_p',
        'neuralActivityCube_q',
        'neuralActivityCube_r',
        'neuralActivityCube_s',
        'neuralActivityCube_u',
        'neuralActivityCube_v',
        'neuralActivityCube_w',
        'neuralActivityCube_x',
        'neuralActivityCube_y',
        'neuralActivityCube_z',
        'neuralActivityCube_greaterThan',
        'neuralActivityCube_comma',
        'neuralActivityCube_apostrophe',
        'neuralActivityCube_tilde',
        'neuralActivityCube_questionMark',
        'neuralActivityTimeSeries',
        'clockTimeSeries',
        'blockNumsTimeSeries',
        'blockList',
        'blockStartDates',
        'goPeriodOnsetTimeBin',
        'delayPeriodOnsetTimeBin',
        'characterCues',
        'meansPerBlock',
        'stdAcrossAllData',
        'arrayGeometryMap']

SAMPLE_DICT_PATH = Path(
    "/home/anukoolpurohit/Documents/Workspace/Nueromatch/NMA-DL/HandwritingBCI/tests/sample_objects")
SAMPLE_DICT_PATH = SAMPLE_DICT_PATH / "sample_dict.pickle"
